Lab #7
PauLOk777/lab_7 pull request #1
Opened 2018-11-15 19:00 UTC by PauLOk777

2018-11-15 19:01 UTC, PauLOk777 commented
@nechaido review pls:)

2018-11-18 13:23 UTC, nechaido commented
Ти хто (Ім'я, група)

2018-11-18 13:54 UTC, PauLOk777 commented
Троцюк Павло, ІП-82

нд, 18 лист. 2018 о 15:23 Dmytro Nechai <notifications@github.com> пише:

> Ти хто (Ім'я, група)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/PauLOk777/lab_7/pull/1#issuecomment-439692571>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AotKVRTBlsoQE2YVtuOXTr6ddi-J6Edmks5uwV9sgaJpZM4Yhtji>
> .
>

2018-11-18 14:40 UTC, nechaido requested changes

2018-11-18 14:40 UTC, nechaido commented on main.cpp
> +const int N = 15;
Глобальные переменные нужно убрать.

2018-11-18 14:40 UTC, nechaido commented on main.cpp
> +void outputSorted();
Зачем тебе две одинаковых функции? Вывод масива не меняется от того отсортирован он или нет.

2018-11-18 14:43 UTC, PauLOk777 commented on main.cpp
> +void outputSorted();
Переробив

2018-11-18 14:43 UTC, PauLOk777 commented on main.cpp
> +void outputSorted();
З виводом шось рілі протупив

2018-11-24 19:35 UTC, nechaido approved these changes
Принято.

2018-12-13 18:39 UTC, merged